### PR TITLE
Knobs and switches styled as in original neural amp modeler

### PR DESCRIPTION
**Pull request by rominator1983**

### CODE REVIEW

**Comment by rominator1983** [comment]
ahhh. did not update screenshots

**Comment by rominator1983** [comment]
ok. updating screenshots really is not that easy for me. @falkTX if you would be so kind?
Other than that I am now finished with my work on the ui and the plugin beside the loading behaviour of https://github.com/mikeoliphant/neural-amp-modeler-lv2/issues/31

**Comment by falkTX** [comment]
no worries on screenshots, I still need to finalize the new tool that generates those, but it needs MOD to release 1.13.2 first anyway.
thanks!

PS: I wonder what to do with the level meters, but best to ask Mike

**Comment by falkTX** [comment]
PS: For generating screenshots I just created https://github.com/moddevices/mod-screenshot that contains my WIP tools for this. if you have latest mod-ui running this should already work, though for non-MOD units you need to adjust the address.

**Comment by rominator1983** [comment]
> PS: I wonder what to do with the level meters, but best to ask Mike

He already mentioned that they are not in use too. I tried without but I liked it better with the meters.

**Pull request merged**
